import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import TopNav from "@/components/navbar/TopNav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Match Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNav />
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
